# Generated by Django 3.1 on 2022-08-15 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_variations"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="variations",
            options={"verbose_name": "variation", "verbose_name_plural": "variations"},
        ),
    ]
